version: '3.8'
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=app
      - MYSQL_DATABASE=remotedesi_dev
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - "dbdata:/var/lib/mysql"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_USER=root
      - DB_NAME=remotedesi_dev
      - DB_PASSWORD=password
      - DB_HOST=db
    volumes:
      - .:/app

volumes:
  dbdata: